apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Name }}-ns
data:
  fluent.conf: |
    # We can use this config to load some default config or load user defined config
    @include vrli.conf
  vrli.conf: |
    <source>
      @id in_tail_container_logs
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/containers/fluentd-containers.log.pos
      tag raw.kubernetes.*
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
    </source>

    # Detect exceptions in the log output and forward them as one log entry.
    <match raw.kubernetes.**>
      @id raw.kubernetes
      @type detect_exceptions
      remove_tag_prefix raw
      message log
      stream stream
      multiline_flush_interval 5
      max_bytes 500000
      max_lines 1000
    </match>

    # Concatenate multi-line logs
    <filter **>
      @id filter_concat
      @type concat
      key message
      multiline_end_regexp /\n$/
      separator ""
    </filter>

    <filter *.**>
      @type record_transformer
      <record>
        fluentdhost ${hostname}
        environment {{ .Values.tag.environment }}
        clustername {{ .Values.tag.clustername }}
        log_type kubernetes
      </record>
    </filter>

    # Enriches records with Kubernetes metadata
    <filter kubernetes.**>
      @id filter_kubernetes_metadata
      @type kubernetes_metadata
      watch false
    </filter>

    <match **>
      @type vmware_loginsight
      scheme {{ .Values.vrli.scheme }}
      ssl_verify {{ .Values.vrli.sslVerify }}
      host {{ .Values.vrli.host }}
      port {{ .Values.vrli.port }}
      path api/v1/events/ingest
      http_method post
      serializer json
      rate_limit_msec 0
      raise_on_error true
      include_tag_key true
      tag_key tag
      http_conn_debug false      
    </match>

